from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_DBConnectionGen(object):
    def setupUi(self, DBConnectionGen):
        DBConnectionGen.setObjectName("DBConnectionGen")
        DBConnectionGen.resize(495, 600)
        self.centralwidget = QtWidgets.QWidget(DBConnectionGen)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 10, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Aero")
        font.setPointSize(22)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 99, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 139, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 179, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 59, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.server = QtWidgets.QLineEdit(self.centralwidget)
        self.server.setGeometry(QtCore.QRect(220, 99, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.server.setFont(font)
        self.server.setObjectName("server")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(220, 149, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(220, 189, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 229, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bebas")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.database = QtWidgets.QLineEdit(self.centralwidget)
        self.database.setGeometry(QtCore.QRect(220, 239, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.database.setFont(font)
        self.database.setObjectName("database")
        self.extention = QtWidgets.QComboBox(self.centralwidget)
        self.extention.setGeometry(QtCore.QRect(220, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.extention.setFont(font)
        self.extention.setObjectName("extention")
        self.extention.addItem("")
        self.extention.addItem("")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(110, 290, 121, 31))
        self.generate.setFlat(False)
        self.generate.setObjectName("generate")
        self.preview = QtWidgets.QPushButton(self.centralwidget)
        self.preview.setGeometry(QtCore.QRect(250, 290, 121, 31))
        self.preview.setObjectName("preview")
        self.preview_text = QtWidgets.QTextBrowser(self.centralwidget)
        self.preview_text.setGeometry(QtCore.QRect(15, 350, 471, 211))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.preview_text.setFont(font)
        self.preview_text.setObjectName("preview_text")
        DBConnectionGen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DBConnectionGen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 495, 21))
        self.menubar.setObjectName("menubar")
        self.menuDBConGen = QtWidgets.QMenu(self.menubar)
        self.menuDBConGen.setObjectName("menuDBConGen")
        DBConnectionGen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DBConnectionGen)
        self.statusbar.setObjectName("statusbar")
        DBConnectionGen.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuDBConGen.menuAction())

        self.retranslateUi(DBConnectionGen)
        QtCore.QMetaObject.connectSlotsByName(DBConnectionGen)

    def retranslateUi(self, DBConnectionGen):
        _translate = QtCore.QCoreApplication.translate
        DBConnectionGen.setWindowTitle(_translate("DBConnectionGen", "MainWindow"))
        self.label.setText(_translate("DBConnectionGen", "Database Connection Generator"))
        self.label_2.setText(_translate("DBConnectionGen", "Server"))
        self.label_3.setText(_translate("DBConnectionGen", "Username"))
        self.label_4.setText(_translate("DBConnectionGen", "Password"))
        self.label_5.setText(_translate("DBConnectionGen", "Extention"))
        self.label_6.setText(_translate("DBConnectionGen", "Database"))
        self.extention.setItemText(0, _translate("DBConnectionGen", ".js"))
        self.extention.setItemText(1, _translate("DBConnectionGen", ".php"))
        self.generate.setText(_translate("DBConnectionGen", "Generate"))
        self.preview.setText(_translate("DBConnectionGen", "Preview"))
        self.menuDBConGen.setTitle(_translate("DBConnectionGen", "DBConGen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DBConnectionGen = QtWidgets.QMainWindow()
    ui = Ui_DBConnectionGen()
    ui.setupUi(DBConnectionGen)
    DBConnectionGen.show()
    sys.exit(app.exec_())
